### PR TITLE
fix: show error when sender is same as recipient

### LINKED ISSUE #19: Transaction with same recipient as sender only fails after signing
A transaction's sender and recipient cannot be the same address. The SendModal however does not detect this case and the transaction only fails to send when sending to the network, after it was signed.

### PR DESCRIPTION
**Pull request by mariofriz**
This PR fixes #19 

## Description

When sender and recipient are the same the transaction only fails during transaction step. It should fail early and inform user.

**Steps to reproduce**
- Copy address of current active address
- Open "Send" modal
- Paste address
- No validation happens and amount input is shown

## Changes
- Add recipient validation (sender address different from recipient address)
- Fix small indentation error

## Todo
- [x] Validate error message
- [ ] Translate error message

### CODE REVIEW

File: src/components/modals/SendModal.vue [hunk 1]
```diff
@@ -141,6 +151,7 @@
                     <LabelInput
                         v-model="message"
                         :placeholder="$t('Add a public message...')"
+                        :disabled="!isValidRecipient"
                         :maxBytes="64"
```
Comment (sisou) [inline src/components/modals/SendModal.vue]: Instead of disabling the `message` LabelInput, the whole section should be hidden, just like the `amount-section`.

**Review by sisou — CHANGES_REQUESTED** [review]

**Comment by sisou** [comment]
@Tammoovernice 
This is the wording suggested for this change. Do you agree or would you suggest differently?
image

**Comment by Tammoovernice** [comment]
> @Tammoovernice
> This is the wording suggested for this change. Do you agree or would you suggest differently?
> image

Let's lose the 'Invalid recipient'. It's tech talk + we can't be sure that the user has the correct recipient but the wrong sender.
I would suggest 'The sender and recipient cannot be identical.' to avoid the more strict 'must'.

**Comment by mariofriz** [comment]
Can someone please explain the i18n process to me? 

Updated the text and remove message input:
Screenshot from 2021-02-25 21 38 07

**Review by sisou — APPROVED** [review]
Regarding i18n: You already extracted the en.po file. After it's merged, we'll push it to Transifex so it can get translated by our translators. Then later, when translated, it will be pulled down in the next deployment.
